<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/JavaLearning/blob/master/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

https://pandas.pydata.org/about/index.html

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

### Importing Pandas

In [ ]:
import numpy as np
import pandas as pd

### Series from lists

In [ ]:
# string
country = ['India','Pakistan','USA','Nepal','Srilanka']
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [ ]:
# integers
runs = [13,24,56,78,100]
runs_ser = pd.Series(runs)
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [ ]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks, index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [ ]:
# setting a name
marks = pd.Series(marks,index=subjects,name='Nitish ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Nitish ke marks, dtype: int64

### Series from dict

In [ ]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks,name='Nitish ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: Nitish ke marks, dtype: int64

### Series Attributes

In [ ]:
# size
marks_series.size

4

In [ ]:
# dtype
marks_series.dtype

dtype('int64')

In [ ]:
# name
marks_series.name

'Nitish ke marks'

In [ ]:
# is_unique
marks_series.is_unique

True

In [ ]:
pd.Series([1,1,2,3,4,5]).is_unique

False

In [ ]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [ ]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# values
marks_series.values

array([ 67,  57,  89, 100])

### Series using read_csv

In [ ]:
# with one col
subs = pd.read_csv('/content/subs.csv').iloc[:, 0]
subs

FileNotFoundError: [Errno 2] No such file or directory: '/content/subs.csv'

In [ ]:
# with 2 cols
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').iloc[:,0]
vk

FileNotFoundError: [Errno 2] No such file or directory: '/content/kohli_ipl.csv'

In [ ]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie').iloc[:,0]
movies

FileNotFoundError: [Errno 2] No such file or directory: '/content/bollywood.csv'

### Series methods

In [ ]:
# head and tail
subs.head()

NameError: name 'subs' is not defined

In [ ]:
vk.head(3)

NameError: name 'vk' is not defined

In [ ]:
vk.tail(10)

NameError: name 'vk' is not defined

In [ ]:
# sample
movies.sample(5)

NameError: name 'movies' is not defined

In [ ]:
# value_counts -> movies
movies.value_counts()

NameError: name 'movies' is not defined

In [ ]:
# sort_values -> inplace
vk.sort_values(ascending=False).head(1).values[0]

NameError: name 'vk' is not defined

In [ ]:
vk.sort_values(ascending=False)

NameError: name 'vk' is not defined

In [ ]:
# sort_index -> inplace -> movies

In [ ]:
Vk = vk.sort_values()
Vk
Vk.sort_values(inplace=True)

NameError: name 'vk' is not defined

In [ ]:
# sort_index -> inplace -> movies
movies

NameError: name 'movies' is not defined

In [ ]:
movies.sort_index(ascending=False,inplace=True)

NameError: name 'movies' is not defined

In [ ]:
movies

NameError: name 'movies' is not defined

### Series Maths Methods

In [ ]:
# count
vk.count()

NameError: name 'vk' is not defined

In [ ]:
movies.count()

NameError: name 'movies' is not defined

In [ ]:
movies

NameError: name 'movies' is not defined

In [ ]:
# sum - > product
subs

NameError: name 'subs' is not defined

In [ ]:
subs.sum()

NameError: name 'subs' is not defined

In [ ]:
subs.product()

NameError: name 'subs' is not defined

In [ ]:
# mean - > median -> mode -> std -> var
subs.mean()
print(vk.median())
print(movies.mode())
print(subs.std())
print(vk.var())

NameError: name 'subs' is not defined

In [ ]:
# min/max
subs.min()

NameError: name 'subs' is not defined

In [ ]:
subs.max()

NameError: name 'subs' is not defined

In [ ]:
# describe
vk.describe()

NameError: name 'vk' is not defined

In [ ]:
subs.describe()

NameError: name 'subs' is not defined

### Series Indexing

In [ ]:
# integer indexing
x = pd.Series([12,13,14,35,46,57,58,79,9])
x[0]

np.int64(12)

In [ ]:
# negative indexing
x[-1]

KeyError: -1

In [ ]:
movies

NameError: name 'movies' is not defined

In [ ]:
movies[0]

NameError: name 'movies' is not defined

In [ ]:
movies['Zor Lagaa Ke...Haiya!']

NameError: name 'movies' is not defined

In [ ]:
movies[-1]

NameError: name 'movies' is not defined

In [ ]:
marks_series

maths       67
english    100
science     89
hindi      100
sst         90
Name: Nitish ke marks, dtype: int64

In [ ]:
marks_series[-1]

In [ ]:
# slicing
vk[5:17]

In [ ]:
# negative slicing
vk[-5:]

In [ ]:
movies[-5:]

In [ ]:
movies[::2]

In [ ]:
# fancy indexing
vk[[1,3,4,5]]

In [ ]:
# indexing with labels -> fancy indexing
movies['2 States (2014 film)']

### Editing Series

In [ ]:
# using indexing
marks_series

In [ ]:
marks_series[1] = 100
marks_series

/tmp/ipykernel_479/3660931059.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks_series[1] = 100

maths       67
english    100
science     89
hindi      100
Name: Nitish ke marks, dtype: int64

In [ ]:
# what if an index does not exist
marks_series['sst'] = 90
marks_series

maths       67
english    100
science     89
hindi      100
sst         90
Name: Nitish ke marks, dtype: int64

In [ ]:
# slicing
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [ ]:
runs_ser[2:4] = [100,100]
runs_ser

0     13
1     24
2    100
3    100
4    100
dtype: int64

In [ ]:
# fancy indexing
runs_ser[[0,3,4]] = [0,0,0]
runs_ser

0      0
1     24
2    100
3      0
4      0
dtype: int64

In [ ]:
# using index label
movies

NameError: name 'movies' is not defined

In [ ]:
movies['2 States (2014 film)'] = 'Alia Bhatt'
movies

### Copy and Views

### Series with Python Functionalities

In [ ]:
# len/type/dir/sorted/max/min
print(len(subs))
print(type(subs))
print(dir(subs))
print(sorted(subs))
print(min(subs))
print(max(subs))

In [ ]:
# type conversion
list(marks_series)

In [ ]:
dict(subs)

In [ ]:
dict(marks_series)

In [ ]:
# membership operator
'2 States (2014 film)' in movies

In [ ]:
'Alia Bhatt' in movies.values

NameError: name 'movies' is not defined

In [ ]:
movies

NameError: name 'movies' is not defined

In [ ]:
# looping
for i in movies.index:
  print(i)

In [ ]:
# Arithematic operator
100 - marks_series

In [ ]:
# Relational operator

vk >= 50

### Boolean Indexing on Series

In [ ]:
# find the no of 50's and 100's scored by kohli
vk >= 50

In [ ]:
vk[vk >= 50]

NameError: name 'vk' is not defined

In [ ]:
vk[vk >= 50].size

In [ ]:
# find number of ducks
vk[vk == 0]

NameError: name 'vk' is not defined

In [ ]:
vk[vk==0].size

In [ ]:
# Count number of day when I had more than 200 subs a day
subs

In [ ]:
subs[subs > 200]

In [ ]:
subs[subs > 200].size

In [ ]:
# find actors who have done more than 20 movies
num_movies = movies.value_counts()
num_movies[num_movies > 20]

### Plotting Graphs on Series

In [ ]:
subs.plot()

In [ ]:
movies.value_counts().head(20).plot(kind='bar')

In [ ]:
movies.value_counts().head(20).plot(kind='pie')

### Some Important Series Methods

In [ ]:
# astype
# between
# clip
# drop_duplicates
# isnull
# dropna
# fillna
# isin
# apply
# copy

In [ ]:
# astype
import sys
sys.getsizeof(vk)

NameError: name 'vk' is not defined

In [ ]:
sys.getsizeof(vk.astype('int16'))

In [ ]:
# between
vk[vk.between(51,99)].size

In [ ]:
subs

In [ ]:
subs.clip(100,200)

In [ ]:
# drop duplicate
temp = pd.series([1,1,2,2,3,3,4,4])
temp

In [ ]:
temp.drop_duplicates(keep='last')

NameError: name 'temp' is not defined

In [ ]:
temp.duplicated().sum()

NameError: name 'temp' is not defined

In [ ]:
vk.duplicated().sum()

In [ ]:
temp = pd.Series([1,2,3,np.nan,5,6,np.nan,8,np.nan,10])
temp

In [ ]:
temp.size

In [ ]:
temp.count()

In [ ]:
# isnull
temp.isnull().sum()

In [ ]:
# dropna
temp.dropna()

In [ ]:
# fillna
temp.fillna(temp.mean())

NameError: name 'temp' is not defined

In [ ]:
# isin
vk[(vk == 49) | (vk == 99)]

In [ ]:
vk[vk.isin([49,99])]

NameError: name 'vk' is not defined

In [ ]:
# apply
movies

In [ ]:
movies.apply(lambda x:x.split()[0].upper())

In [ ]:
subs

In [ ]:
subs.apply(lambda x:'good day' if x > subs.mean() else 'bad day')

In [ ]:
subs.mean()

In [ ]:
# copy

In [ ]:
vk

In [ ]:
new = vk.head()

In [ ]:
new

In [ ]:
new[1] = 1

In [ ]:
new = vk.head().copy()

In [ ]:
new[1] = 100

In [ ]:
new

In [ ]:
vk